//This file contains the words for the audio jargon generator.


export const audioJargon = {
    words0: [
        '48K',
        'AAC',
        'AC-3',
        'AC97',
        'ACPA',
        'AGC',
        'AIFF',
        'APAC',
        'ASIO',
        'AV',
        'AWAC',
        'CBR',
        'CD-DA',
        'CD-ROM',
        'CPS',
        'DAI',
        'DAW',
        'DSP',
        'FLAC',
        'FOH',
        'HDA',
        'M4A',
        'MP3',
        'RMS',
        'SPDIF',
        'THD',
        'THX',
        'VAIO',
        'VST',
        'VST3',
        'WAV',
        'WMA'
    ],

    words1: [
        'aliased',
        'ambient',
        'analog',
        'automated',
        'auxiliary',
        'balanced',
        'Baxandall',
        'cardioid',
        'condenser',
        'digital',
        'dynamic',
        'graphic',
        'harmonic',
        'high-pass',
        'low-pass',
        'master',
        'mono',
        'multi-band',
        'multi-track',
        'peak',
        'phantom',
        'resonant',
        'stereo',
        'surround',
        'transient',
        'unbalanced',
        'vintage',
        'virtual'
    ],

    words2: [
        'amplifier',
        'bitrate',
        'channel',
        'converter',
        'delay',
        'distortion',
        'driver',
        'exciter',
        'fader',
        'feedback',
        'filter',
        'frequency',
        'gain',
        'ground loop',
        'headroom',
        'impedance',
        'latency',
        'limiter',
        'mixer',
        'noise floor',
        'plugin',
        'preamp',
        'processor',
        'ratio',
        'reverb',
        'sample',
        'sidechain',
        'signal',
        'soundboard',
        'threshold',
        'tone',
        'transducer',
        'waveform'
    ],

    words3: [
        'adjust',
        'amplify',
        'attenuate',
        'autotune',
        'boost',
        'broadcast',
        'clip',
        'compress',
        'cross-fade',
        'cut',
        'dial in',
        'dither',
        'encode',
        'EQ',
        'level',
        'mix down',
        'mix',
        'mute',
        'normalize',
        'phase-shift',
        'quantize',
        'shelve',
        'sweep'
    ],

    words4: [
        'amplifying',
        'attenuating',
        'autotuning',
        'boosting',
        'broadcasting',
        'clipping',
        'compressing',
        'cross-fading',
        'dialing in',
        'dithering',
        'encoding',
        'EQing',
        'leveling',
        'mixing down',
        'mixing',
        'muting',
        'normalizing',
        'phase-shifting',
        'quantizing',
        'shelving',
        'sweeping'
    ],

    sentences: [
        "Ever since {4} the {2} on my {2}, I can totally {3} more {1} {2}s in my {2}.",
        "I like to {3} my {1} {1} {2} through my {0} {2}, it's easier to {3} that way.",
        "I've never liked their {1} {2}s, my {1} {0} {2} can {3} so much better.",
        "If you want to {3}, try using the {0} {1} {2}, it's my little trick.",
        "If you {3} the {0} {2}, it's easier to {3} the {0} {2}.",
        "See, the {2} is causing {1} {2} in the {0} {2}. That's why it's best to {3} using a {0} {2}.",
        "Some people only hear the {1} {2}, but I'm picking up the {0} {1} {2} as well.",
        "That {2} is just a poor man's {0} {2}. To really understand {4}, you need to {3} with only {1} {2}s to work with.",
        "The problem is this {2} has its own {1} {0} {2}. If you had just gone with the {1} {2}, it would have been easier to {3}.",
        "They say {1} {0} is the next big thing, but I'm sticking with my {0} {1} {2}.",
        "This {2} has its own {1} {0} {2}, the {1} {2} sounds amazing.",
        "You can get away with {4} the {1} {2}, but then you run the risk of the {2} getting into your {0} {2}.",
        "You should try using the {1} {0} {2}, it will {3} your {1} {2} like you wouldn't believe.",
        "{4} has never been the same since I lost my {1} {1} {2}, now I have to use my {2} for {4}.",
        "{4} your {1} {2} will really bring out the {1} {1} {2} when you {3} the {2}."
    ]
}
