// This file contains the words for the educational nonsense generator.


export const educationJargon = {
    verbs: [
        'advocate',
        'agendize',
        'aggregate',
        'assess',
        'aesthetics',
        'benchmark',
        'cultivate',
        'deliver',
        'deploy',
        'disaggregate',
        'discern',
        'disintermediate',
        'drive',
        'embrace',
        'empower',
        'enable',
        'engage',
        'engineer',
        'enhance',
        'envision',
        'evolve',
        'exemplify',
        'expedite',
        'exploit',
        'extend',
        'facilitate',
        'generate',
        'grow',
        'harness',
        'implement',
        'innovate',
        'integrate',
        'investigate',
        'iterate',
        'leverage',
        'maximize',
        'mesh',
        'metacognate',
        'morph',
        'motivate',
        'operationalize',
        'optimize',
        'orchestrate',
        'pool',
        'prioritize',
        'problematize',
        'recontextualize',
        'reinvent',
        'repurpose',
        'revisit',
        'revolutionize',
        'seize',
        'share out',
        'strategize',
        'streamline',
        'synergize',
        'synthesize',
        'target',
        'transform',
        'transition',
        'triangulate',
        'unleash',
        'unpack',
        'utilize',
        'visualize'
    ],

    adjectives: [
        'actionable',
        'assessment-driven',
        'authentic',
        'blended',
        'bottom-up',
        'brain-compatible',
        'child-centered',
        'classroom-based',
        'collaborative',
        'college and career ready',
        'collegial',
        'compelling',
        'competency-based',
        'constructivist',
        'cooperative',
        'critical',
        'cross-curricular',
        'customer-driven',
        'data-driven',
        'developmentally appropriate',
        'discipline-based',
        'diverse',
        'dynamic',
        'efficient',
        'emerging',
        'evidence-based',
        'flipped',
        'global',
        'group-based',
        'hands-on',
        'holistic',
        'impactful',
        'innovative',
        'inquiry-centered',
        'integrated',
        'interactive',
        'interdisciplinary',
        'intersegmental',
        'intuitive',
        'learner-centered',
        'learning-intensive',
        'literature-based',
        'mastery-focused',
        'meaning-centered',
        'metacognitive',
        'mission-critical',
        'multidimensional',
        'multidisciplinary',
        'multi-media',
        'objective',
        'open-ended',
        'outcome-based',
        'over-arching',
        'peer-based',
        'performance-based',
        'performance-driven',
        'proactive',
        'problem-based',
        'process-based',
        'real-time',
        'real-world',
        'research-based',
        'revolutionary',
        'school-based',
        'school-to-work',
        'shared',
        'site-based',
        'socio-emotional',
        'social contructivist',
        'standards-based',
        'strategic',
        'strengths-based',
        'student-centered',
        'subjective',
        'synergistic',
        'team taught',
        'technology-infused',
        'technology-enhanced',
        'thematic',
        'top-down',
        'visionary'
    ],

    nouns: [
        'action plans',
        'action-items',
        'alignment',
        'applications',
        'articulation',
        'assessment',
        'best practices',
        'brain research',
        'business partnerships',
        'capacity',
        'classification',
        'cohorts',
        'concept maps',
        'Common Core Standards',
        'communities',
        'competencies',
        'content',
        'convergence',
        'career and technical education',
        'critical thinking',
        'culminating products',
        'curiosity',
        'curriculum compacting',
        'curriculum integration',
        'curriculum',
        'debriefs',
        'decision-making',
        'dialogue',
        'differentiated lessons',
        'education',
        'efficacies',
        'enduring understandings',
        'engagement structures',
        'enrichment',
        'ESLR\'s',
        'experiences',
        'explicit direct instruction',
        'facilitators',
        'functionalities',
        'goals',
        'guiding coalitions',
        'growth mindsets',
        'higher-order thinking',
        'infrastructures',
        'initiatives',
        'inquiry',
        'instruction',
        'interfaces',
        'learning',
        'Learning Focused Lesson Plans',
        'learning styles',
        'liaisons',
        'life-long learning',
        'living documents',
        'manipulatives',
        'mastery learning',
        'methodologies',
        'models',
        'multiple intelligences',
        'need-to-knows',
        'networks',
        'Next Generation Science Standards',
        'niches',
        'objectives',
        'opinions',
        'outcomes',
        'paradigms',
        'paradigms',
        'paradoxes',
        'pedagogy',
        'policies',
        'practices',
        'presentations',
        'problem-solving',
        'processes',
        'proficiencies',
        'relationships',
        'risk-takers',
        'scaffolding',
        'schemas',
        'schools',
        'school-to-work programs',
        'SMART goals',
        'solutions',
        'staff development',
        'stakeholders',
        'strategies',
        'student success',
        'Student Learning Maps',
        'styles',
        'synergies',
        'systems',
        'teaching',
        'technologies',
        'terminal and enabling objectives',
        'trans-disciplinarity',
        'units'
    ],

    phrases: [
        'across content areas',
        'across spatial and temporal scales',
        'across the curricular areas',
        'across cognitive and affective domains',
        'for high-performing seats',
        'for our 21st Century learners',
        'in authentic, "real world" scenarios',
        'in closing the achievement gap',
        'in data-driven schools',
        'outside the box',
        'throughout the Big Ideas',
        'through cognitive disequilibrium',
        'through the collaborative process',
        'through the experiential based learning process',
        'through high impact practices',
        'through the use of centers',
        'throughout multiple modalities',
        'via thinking, learning and doing',
        'via self-reflection',
        'with a laser-like focus',
        'within a balanced literacy program',
        'within professional learning communities',
        'within the core curriculum',
        'within the new paradigm',
        'within the Zone of Proximity',
        'with synergistic effects'
    ]
}
