// This file contains the words for the perfect excuse generator.


export const excuseJargon = {
    words0: [
        'boss',
        'brother',
        'butler',
        'cat',
        'CIA contact',
        'colleague',
        'dad',
        'dog',
        'ex-professor\'s former psychiatrist',
        'friend',
        'grandma',
        'grandpa',
        'imaginary friend',
        'intern',
        'maid',
        'mentor',
        'mom',
        'neighbor',
        'personal space cowboy',
        'personal trainer',
        'pet alien',
        'pet tiger',
        'pool boy',
        'professor',
        'roommate',
        'secretary',
        'sister',
        'son\'s girlfriend'
    ],

    words1: [
        'accidentally',
        'admittedly',
        'angrily',
        'carelessly',
        'crazily',
        'deliberately',
        'endlessly',
        'explicitly',
        'explosively',
        'fatally',
        'furiously',
        'intentionally',
        'knowingly',
        'loudly',
        'purposely',
        'recklessly',
        'secretly',
        'silently',
        'spontaneously',
        'subtly',
        'surreptitiously',
        'unintentionally',
        'unwittingly',
        'viciously'
    ],

    words2: [
        'application',
        'assignment',
        'composition',
        'deliverable',
        'disk',
        'exam',
        'final draft',
        'homework',
        'laptop',
        'model',
        'notebook',
        'paper',
        'poster',
        'presentation',
        'program',
        'project',
        'proposal',
        'report',
        'research',
        'rough draft',
        'second draft',
        'task list',
        'thesis'
    ],

    words3: [
        'ate',
        'blew up',
        'broke',
        'buried',
        'buried',
        'destroyed',
        'drank',
        'dropped',
        'hid',
        'microwaved',
        'painted on',
        'peed on',
        'poured water on',
        'puked on',
        'ripped',
        'ruined',
        'sat on',
        'set fire to',
        'smashed',
        'sold',
        'spilled coffee on',
        'stole',
        'swallowed',
        'tainted',
        'threw up on',
        'tore up'
    ],

    words4: [
        'add to',
        'commit to',
        'complete',
        'continue',
        'contribute to',
        'deliver',
        'do well on',
        'do',
        'finalize',
        'finish',
        'follow through on',
        'print',
        'put effort into',
        'send',
        'sign off on',
        'submit',
        'work on',
        'write'
    ],

    sentences: [
        "After my {0} {1} {3} my {2}, I obviously couldn't {4} it.",
        "After my {0} {3} my {2}, I {1} {3} their {2}, so neither of us can {4} it.",
        "I couldn't {4} my {2} because my {0} {3} it!",
        "I had a bad morning, my {0} {1} {3} my {0}'s {2}, then {3} my {2}.",
        "I had issues with my {2}, my {0} {3} it, then {1} {3} my {2}!",
        "I want to {4} my {2}, but my {0} said my {0} {1} {3} it!",
        "I {1} {3} my {2}, it will be hard to {4} it now.",
        "My {0} {1} {3} my {2}, so I couldn't {4} my {2}!",
        "My {0} {3} my {2}, because they thought my {0}'s was better.",
        "Remember when my {0} {3} my {2}? Well, today they {1} {3} it too, so I can't {4} it.",
        "The thing is, I can't {4} my {2} because my {0} {3} it, probably {1}."
    ]
}
