// This file contains the words for the hollywood tech jargon generator.


export const techJargon = {
    words0: [
        'AAC',
        'ADP',
        'AGP',
        'AI',
        'ASCII',
        'BIOS',
        'CD-ROM',
        'CGI',
        'COM',
        'CPU',
        'CSS',
        'DDR',
        'DHCP',
        'EXE',
        'FTP',
        'GB',
        'GUI',
        'HDD',
        'HTTP',
        'IDE',
        'IP',
        'MAC',
        'MP3',
        'PCI',
        'PHP',
        'PNG',
        'PPPoE',
        'RAM',
        'RSS',
        'RX',
        'SDD',
        'SDRAM',
        'SMS',
        'SMTP',
        'SQL',
        'SSD',
        'SSL',
        'TCP',
        'THX',
        'TPS',
        'UDP',
        'USB',
        'VGA',
        'XHTML',
        'XML',
        'Y2K'
    ],

    words1: [
        '1080p',
        '56k',
        'analog',
        'auxiliary',
        'back-end',
        'backup',
        'bluetooth',
        'central',
        'cross-platform',
        'digital',
        'ethernet',
        'fiber optic',
        'haptic',
        'high speed',
        'mobile',
        'multi-byte',
        'neural',
        'online',
        'open-source',
        'optical',
        'primary',
        'redundant',
        'solid state',
        'unicode',
        'virtual',
        'visual',
        'wireless'
    ],

    words2: [
        'address',
        'alarm',
        'antenna',
        'application',
        'array',
        'array',
        'bandwidth',
        'bus',
        'capacitor',
        'card',
        'circuit',
        'driver',
        'feed',
        'firewall',
        'form factor',
        'hard drive',
        'interface',
        'internet',
        'mainframe',
        'malware',
        'matrix',
        'microchip',
        'monitor',
        'network',
        'panel',
        'pixel',
        'port',
        'processor',
        'program',
        'protocol',
        'sensor',
        'spyware',
        'system',
        'transistor',
        'transmitter',
        'virus'
    ],

    words3: [
        'attach',
        'back up',
        'bypass',
        'calculate',
        'compress',
        'connect',
        'copy',
        'disconnect',
        'encode',
        'generate',
        'hack',
        'index',
        'inject',
        'input',
        'navigate',
        'network',
        'override',
        'parse',
        'program',
        'quantify',
        'reboot',
        'shut down',
        'synthesize',
        'transcode',
        'transmit'
    ],

    words4: [
        'attaching',
        'backing up',
        'bypassing',
        'calculating',
        'compressing',
        'connecting',
        'copying',
        'disconnecting',
        'encoding',
        'generating',
        'hacking',
        'indexing',
        'injecting',
        'inputting',
        'navigating',
        'networking',
        'overriding',
        'parsing',
        'programming',
        'quantifying',
        'rebooting',
        'shutting down',
        'synthesizing',
        'transcoding',
        'transmitting'
    ],

    sentences: [
        "I'll {3} the {1} {0} {2}, that should {3} the {0} {2}!",
        "If we {3} the {2}, we can get to the {0} {2} through the {1} {0} {2}!",
        "My {0} {2} is down, our only choice is to {3} and {3} the {1} {2}!",
        "Send the {1} {2} into the {2}, it will {3} the {2} by {4} its {0} {2}!",
        "The {0} {2} is down, {3} the {1} {2} so we can {3} the {0} {2}!",
        "They're inside the {2}, use the {1} {0} {2} to {3} their {2}!",
        "Try to {3} the {0} {2}, maybe it will {3} the {1} {2}!",
        "Use the {1} {0} {2}, then you can {3} the {1} {2}!",
        "We need to {3} the {1} {0} {2}!",
        "You can't {3} the {2} without {4} the {1} {0} {2}!",
        "{4} the {2} won't do anything, we need to {3} the {1} {0} {2}!"
    ]
}
